sudo: false
language: python
# must be trusty for 'python3-pip' to be available
dist: trusty 
python:
  - 3.5
  - 3.6
# lets install pip3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-pip python3-magic python3-pytest
# command to install dependencies
install:
  - pip3 install .
  - travis_retry pip3 install -U pytest>=4.0.1 pytest-cov>=2.6.0;
# command to run tests
script:
  - pytest --version;
  - python3 -m pytest --version;
  - python3 -m pytest tests/
