language: python
sudo: required
dist: trusty # otherwise 'python3-pip' won't be available
before_install:
- sudo apt-get update -qq
- sudo apt-get install python3 python3-pip
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
